### ISSUE TITLE
Map keys

### ISSUE THREAD

**Issue by rmartins90** [FiguredLimited/vue-mc#22]
I want to make a response keys mapping before requests are made and before response is assigned to model. Is this possible without overriding methods like onFetchSuccess()?

One thing that could work would having different mutators for responses and requests.

**Comment by rtheunissen** [comment]
There are two methods you can use to handle this. They're both preserved with semver so it's safe to override them. They are `getSaveData` and `update`. However, I think we should rename `update` to something like `useSavedData` or `applySave` or `setSaveData` to be consistent with the language of `getSaveData`. 

In the meantime, you can do this:
```js
getSaveData() {
    let data = super.getSaveData(); // Don't need to, can use this.attributes instead
    
    // Adjust the data, map keys etc.

    return data; 
}

update(data) {
    // Reverse what the server responded with to match your data structure.
}
```

While this works, it shouldn't be necessary. Your controller should define and transform a serialised representation of your model so that it can accept and receives the same schema.

What's your use case here?

**Comment by rmartins90** [comment]
This is necessary once I don't have control on backend API and only on frontend application.

**Comment by rtheunissen** [comment]
Oh right, that makes a lot of sense. I didn't consider the situation where you might not have control over the backend. Let me know if overriding those methods don't cover your use case. 👍

**Comment by rmartins90** [comment]
It works. It would be great to support this feature in a mutators way..

**Comment by rmartins90** [comment]
Update method doesn't work for fetch for example. I'm trying to make a login method, on getRequest().send() success I'm calling onFetchSuccess but it does not pass by update method. I can't change it to assign method because it's used in both ways (frontend to API and API to frontend). Do you have any suggestions?
