### ISSUE TITLE
Dependency on globally installed _ (lodash)?

### ISSUE THREAD

**Issue by kvdveer** [FiguredLimited/vue-mc#4]
There seems to be a dependency on the underscore symbol, which not only requires lodash installed (as mentioned in dependencies), but also installed globally (which is typically not acceptable).

Source location: (https://github.com/FiguredLimited/vue-mc/blob/d5e15e4aefb75e26c58cbf4e73d6f28f15a05651/src/Structures/Model.js#L9)

**Comment by lucafaggianelli** [comment]
The same applies for Vue, I needed to add `global.Vue = Vue` to make it work.

Looking at the test index.js, I fear I need to include also other libs:
https://github.com/FiguredLimited/vue-mc/blob/master/test/index.js

Moreover for lodash, it would be better to include a function at once, as per your need, instead of including the entire lib as it's quite big.

**Comment by rtheunissen** [comment]
**This is now a work in progress on the 0.2 branch**. See https://github.com/FiguredLimited/vue-mc/pull/13

> Moreover for lodash, it would be better to include a function at once, as per your need, instead of including the entire lib as it's quite big.

Rollup does that for us. ✨
