### ISSUE TITLE
item.save() sets my item to default values

### ISSUE THREAD

**Issue by haayman** [FiguredLimited/vue-mc#64]
I'm using a backend that returns {result: 'ok'} when an update was succesful. 
However : 
item.onSaveSuccess() calls 
this.update({result:'ok'} which in turn calls 
this.assign({result:ok}) which calls 
this.set(defaultsDeep({}, {result:ok}, cloneDeep(this.defaults())));

and presto: item is set to all defaults

I wonder how calling this.update() doesn't preserve the original content?

the comment in Model.update is:
 // A plain object implies that we want to update the model data.
                // It's not a requirement to respond with a complete dataset,
                // eg. a response to a patch request might return partial data.

which is entirely true, but that's not what's happening.

**Comment by rtheunissen** [comment]
So what should be happening is a merge of defaults + existing attributes + incoming. That makes sense to me. Thank for bringing this up. 👍

**Comment by rtheunissen** [comment]
@haayman this has now been fixed in master but not tagged yet.

**Comment by haayman** [comment]
How can I obtain this version then?

I just thought of this: the main problem actually is that the save() action assumes that the response of the PUT should be merged with the content of the data and nothing can be done to prevent this. I don't think that this assumption is correct. I think the response should be ignored, or we should get the choice what to do with it

**Comment by rtheunissen** [comment]
> How can I obtain this version then?

We're about to release a major version upgrade because validation has changed in a way that breaks backward compatibility. What I'll do is apply this fix to the current version and tag that.

> I just thought of this: the main problem actually is that the save() action assumes that the response of the PUT should be merged with the content of the data and nothing can be done to prevent this. I don't think that this assumption is correct. I think the response should be ignored, or we should get the choice what to do with it

The convention to merge the return data is valid. Usually that data would include attributes like `id`, which can only be set when the record is created. The model would need to know about this `id`. 

This project allows you to return nothing at all, or partial data to patch. If your response returns something like `{"result": "ok"}`, you can override how that response is handled, or adjust the response itself. We use HTTP status codes to indicate success/failure, rather than the response body, which is what dictated the convention for the handling of response data.

**Comment by rtheunissen** [comment]
This has now been released as part of 0.3.0
