### ISSUE TITLE
nested collection problem

### ISSUE THREAD

**Issue by Avaar0032** [FiguredLimited/vue-mc#65]
I have a model that have a collection as one of properties and i cant add new models 
in that collection. It throw the error 'Error: Collection is not valid'. I find out that error is 
happen because field _uid that defined in Base class is disappear on nested collection 
because lodash deepClone doesn get it.

Or maybe there is another way to create a model with array of another model in the property?

**Comment by rtheunissen** [comment]
We haven't come up with a solution for proper support for nested instances yet. There is an open issues addressing this #36 and #39. At this stage, I would advice that you work around the requirement to nest instances. This is an issue that's on the top of the list because it's such a common use case.
