### ISSUE TITLE
Required fields not working when saving collections

### ISSUE THREAD

**Issue by chillcaw** [FiguredLimited/vue-mc#72]
On my model my fields are"
```javascript
// I have all these types imported
// All the other validation rules seem to work asides from required
validation() {
    return {
        attribute1: integer.and(gte(1)).and(required),
        attribute2: dateformat('YYYY-MM-DD').and(required),
        attribute3: number.and(required),
        attribute4: number.and(required),
    }
}
```

I have a collection that holds these models, when I save the collection model objects that don't have all the required fields pass validation and get sent in my payload to the back end.

Example:
This object below will pass validation even through attribute4 is marks as required in the model:
```javascript
let obj = new MyModel({
    attribute1: 32123,
    attribute2: '2018-07-09',
    attribute3: 23452345,
})
```

I have tried explicitly defining options to force validation (even through the default for `validateOnSave` is `true` and I still can figure out how to force my validation rules.
This seems to only happen will the `required` constraint, when saving collections bad formats are always caught.

**Comment by rtheunissen** [comment]
Thanks for bringing this up, I'll see if I can write a failing test for it. 👍

**Comment by chillcaw** [comment]
For anyone else who is having this same issue, you can default the fields to a type that will fail validation, this isn't ideal but a simple temporary fix none the less.

```javascript
let obj = new MyModel({
    attribute1: 32123,
    attribute2: '2018-07-09',
    attribute3: 23452345,
});
```

```javascript
defaults() {
    return {
        // null will fail the validation check for `attribute4`
        attribute1: null,
        attribute2: null,
        attribute3: null,
        attribute4: null,
   }
}

validation() {
    return {
        attribute1: integer.and(gte(1)).and(required),
        attribute2: dateformat('YYYY-MM-DD').and(required),
        attribute3: number.and(required),
        attribute4: number.and(required),
   }
}
```

**Comment by rtheunissen** [comment]
@chillcaw I think what you have right there is not a temporary fix but the intended setup for a model. You should specify a default value for every attribute you intend to use. Because `attribute4` doesn't exist in the attributes object, the validation rule for it will never be called.

This is because query the validation rules for each attribute (if any), rather than the attribute for each key in `validation()`. By not having a default value, it's as if that attribute was never declared. You must either pass an initial value for it or define a default, even if that default is undefined.
