### ISSUE TITLE
Mismatching signatures in onFatalSaveFailure()

### ISSUE THREAD

**Issue by BehindTheMath** [FiguredLimited/vue-mc#82]
1. [`Model.onFatalSaveFailure()`](https://github.com/FiguredLimited/vue-mc/blob/3962dafebc8752aa9d24d3b325bd010c847882ce/src/Structures/Model.js#L1008) takes a single parameter, `error`, and doesn't use it at all.
2. [`Collection.onFatalSaveFailure()`](https://github.com/FiguredLimited/vue-mc/blob/3962dafebc8752aa9d24d3b325bd010c847882ce/src/Structures/Collection.js#L854) calls `Model.onFatalSaveFailure()` with 2 parameters, `error` and `response`.

**Comment by rtheunissen** [comment]
Hmm cases like these are often "here are some arguments that you can use if you want to". I think we should require those arguments for the sake of consistency even if we don't use them today. There's no harm in passing them.

I think we should use strict types for all internal functions and where it makes sense otherwise. There are very few cases where inference makes more sense.

**Comment by rtheunissen** [comment]
Keep in mind that these methods were intended to be overridden, so just because the default implementation doesn't use those args, I'd still like to make them available.

**Comment by BehindTheMath** [comment]
So in TS, should I mark those parameters as optional?

**Comment by rtheunissen** [comment]
I think they should be required, even if the function doesn't use them.

**Comment by BehindTheMath** [comment]
Then `Model.onFatalSaveFailure()` will have to be changed to take 2 parameters.

**Comment by rtheunissen** [comment]
All success methods should receive the response and all failures should receive the response and the error.
