### ISSUE TITLE
Loading entire lodash library

### ISSUE THREAD

**Issue by haayman** [FiguredLimited/vue-mc#89]
My script is huge and analysis shows that vue-mc and the validation library both include the entire lodash library. which is around 527 KB.  This is by far the biggest library in my script. Could you please load just the functions that are actually used?

**Comment by rtheunissen** [comment]
How are you building your script?

**Comment by haayman** [comment]
Webpack

Op do 15 nov. 2018 05:52 schreef Rudi Theunissen <notifications@github.com:

**Comment by rtheunissen** [comment]
This should now be improved in `0.5.0`, please report so we can close if fixed.

**Comment by haayman** [comment]
line 9 of vue-mc.js still says

`var lodash = require('lodash')`

The impact on the size is huge:

![capture](https://user-images.githubusercontent.com/683823/48604731-0fcad380-e97b-11e8-88cd-fe4f835fa881.PNG)

**Comment by rtheunissen** [comment]
What tool did you use to generate that image? 😮

**Comment by haayman** [comment]
webpack-bundle-analyzer

**Comment by rtheunissen** [comment]
If you use `import` instead of `require`, does it use the `vue-mc.es.js` file? If I use `import method from 'lodash/method', it appears to inline that dependency, which is not what we want either, as you may be including that elsewhere in your library and I'm not sure if webpack can be aware of that. 

I'm noticing that the validation component is also quite large, is that vue-mc validation?

**Comment by haayman** [comment]
Yes, that's vue-mc validation. I find that strange, because I only load a
few validation functions

Op vr 16 nov. 2018 18:52 schreef Rudi Theunissen <notifications@github.com:

**Comment by haayman** [comment]
I always use import

Op vr 16 nov. 2018 19:29 schreef Arjen Haayman <arjen.haayman@gmail.com:

**Comment by rtheunissen** [comment]
As an experiment, can you swap your vue-mc.es.js and vue-mc.js files? I'm curious to see what happens when you try to import from that file instead. I'm setting up a little test to debug this further in the meantime.

**Comment by haayman** [comment]
It'll take a few days before I'll have that opportunity

Op vr 16 nov. 2018 20:05 schreef Rudi Theunissen <notifications@github.com:

**Comment by fillefilip8** [comment]
Happens for me as well:
![img](https://i.mlgimg.xyz/127daccd.png)

Same issue as @haayman. at line 6 there is that big require statement for lodash.

**Comment by djsmedes** [comment]
Couple of things that may be useful here -

1. The webpack build analyzer is already available to you if you're using the Vue CLI - you can run `./node_modules/.bin/vue-cli-service build --report` ([among other ways](https://cli.vuejs.org/guide/cli-service.html)) to generate a report.html which you can then open in the browser.

2. In order for `vue-mc.es` to import lodash and actually make use of the tree-shaking to only get what it needs, apparently it must import `lodash-es`. I guess vanilla lodash does not support tree-shaking.

3. It appears that vue is not a peer dependency of vue-mc as the repo stands right now. I have never dealt with publishing to npm so I don't quite understand what's going on, but vue-mc has vue inside its own `node_modules` folder and is pulling it in from there.

What my build looks like in current state - note the doubling-up on `vue.runtime.esm`:
![current_state](https://user-images.githubusercontent.com/7870631/53674569-d46bc080-3c5c-11e9-9539-56e3daac6e6a.png)
This is 330.30 KiB parsed size.

What happens if I delete vue from vue-mc's internal `node_modules` folder:
![no_double_vue](https://user-images.githubusercontent.com/7870631/53674657-6ecc0400-3c5d-11e9-92df-a2b4f2e2580c.png)
269.54 KiB parsed size.

Now if I switch the imports in my own code from `vue-mc` to `vue-mc/vue-mc.es` nothing changes; but after doing that, if I go into `vue-mc.es` and change the import from `lodash` to `lodash-es` I get this:
![final](https://user-images.githubusercontent.com/7870631/53674744-177a6380-3c5e-11e9-9023-42ef2a0395b3.png)
221.67 KiB parsed size. Note the difference in my own `lodash-es` imports from the previous image; webpack is now sharing those with the ones from vue-mc.

So it seems there are two things to do here -
1. Make vue actually a peer dependency. Fix whatever is happening with npm.
2. Change the lodash import to lodash-es in `vue-mc.es` - I'm not sure what the ramifications of doing this are. It will probably break a bunch of peoples' builds, so I doubt this is something you can just decide to do on a whim.

**Comment by haayman** [comment]
Isn't it a lot better to just import the lodash function that is actually
used instead of the entire library? Lodash supports this. Shouldn't be too
hard to determine.

**Comment by djsmedes** [comment]
Ah, I think you’re right. I got caught up in the tree-shaking and somehow the “you might break everyone’s projects” bit didn’t cause me to take a step back and reconsider. 

You’re saying to do imports like `import cloneDeep from “lodash/cloneDeep”` rather than `import { cloneDeep } from “lodash”` right?

Do you have any insight on the other thing, where I’m seeing vue.runtime.esm twice? It looks like that’s not happening for you, maybe I’m just doing something wrong here?

**Comment by haayman** [comment]
I'm afraid that doesn't happen here

Op di 5 mrt. 2019 05:58 schreef Daniel Smedema <notifications@github.com>:

**Comment by haayman** [comment]
> You’re saying to do imports like `import cloneDeep from “lodash/cloneDeep”` rather than `import { cloneDeep } from “lodash”` right?

Yes, this is what I mean. This will have no negative side-effects

**Comment by AndreasHerss** [comment]
i'm seeing the same as you @djsmedes with double up on vue.js, meaning huge size compared to what it should be :S

**Comment by djsmedes** [comment]
I have an idea for a fix there actually, perhaps in vue-mc's package.json, switching vue from a `dependency` to a `peerDependency` + `devDependency` (and for that matter, lodash and axios as well). I will test that out when I get a chance and see if it resolves the issue.

Out of curiosity, @AndreasHerss and @haayman - are you using yarn or npm for the project that is making use of vue-mc? I'm wondering if there's some odd interaction since vue-mc uses yarn but I am using vanilla npm.

**Comment by AndreasHerss** [comment]
@djsmedes i'm using yarn :)

**Comment by haayman** [comment]
I'm quite puzzled why you wouldn't implement my suggestion to just load the
functions that are actually used? It will take you at most an hour to
implement?
I'm using npm. But that's just for installing, not for building?

**Comment by djsmedes** [comment]
@haayman - sorry, I should probably open up another issue for the other issue I'm seeing (that it seems not everyone is). For the lodash import issue, I have already submitted a PR doing exactly as you suggested.

@rtheunissen - when you get a chance could you take a quick look at #104? Thanks!

**Comment by rtheunissen** [comment]
This has been fixed and released as part of [v0.6.0](https://github.com/FiguredLimited/vue-mc/releases/tag/v0.6.0).
